<template>
  <UButton
    color="primary"
    variant="subtle"
    icon="i-lucide-github"
    to="https://github.com/thadius83/deep-research-web-ui"
    target="_blank"
  >
    GitHub
  </UButton>
</template>
